"""memory_evidence_links

Revision ID: 849c0df467ba
Revises: bdc2ae95a5c2
Create Date: 2026-09-28 15:08:53.966640
"""

import sqlalchemy as sa
from alembic import op

revision = "849c0df467ba"
down_revision = "bdc2ae95a5c2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memory_evidence",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("memory_id", sa.String(length=32), nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.event_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["memory_id"], ["memories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("memory_id", "event_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("memory_evidence")
    # ### end Alembic commands ###
